topological.cpp File Reference
topological.cpp File Reference
#include <iostream>
#include <unordered_map>
#include <fstream>
#include <stdlib.h>
#include <vector>
#include <string>
Classes
class Node
Node class that makes up the graph.
Functions
void visit (Node *inNode, vector< Node * > &store)
Visits node and adjacent nodes.
int main (int argc, char **argv)
Main method. Performs topological sort.
Function Documentation
int main (int argc, char ** argv)
Main method. Performs topological sort.
This function takes a filename as its single command line argument. The file contains a list of edges. The output is the classes prrinted in a topologically sorted order.
Author
Ben Haines
Version
0.1
Date
12/02/14
References Node::addEdge(), and visit().
void visit (Node * inNode, vector< Node * > & store)
Visits node and adjacent nodes.
This function visits the node passed as an argument and then recursively visits all of its adjacent nodes.
Parameters
inNode Node to visit.
store Vector that holds the topological order of nodes.
Author
Ben Haines
Version
0.1
Date
12/02/14
References Node::adj, Node::mark, and Node::setMark().
Referenced by main().